### ISSUE TITLE
Gradio 에 tool Issues

### ISSUE THREAD

**Issue by ffe4el** [jbnu-orb/orb#15]
Gradio에 tool 인자를 넣을 수 있는걸로 알고 있는데, 계속해서 오류가 나네요... 

해결가능한 부분일까요?

**Comment by riverallzero** [comment]
어떤 tool 말하시는 건가요?

**Comment by ffe4el** [comment]
gr.Image() 여기에 tool='sketch' 인자를 넣어서, 그림 위에 sketch해서 mark.png 를 만들고 싶어요!

**Comment by riverallzero** [comment]
> gr.Image() 여기에 tool='sketch' 인자를 넣어서, 그림 위에 sketch해서 mark.png 를 만들고 싶어요!

https://github.com/gradio-app/gradio/issues/3248, 참고하면 좋을 것 같네요!

**Comment by ffe4el** [comment]
보내주신 사이트를 찾아보니 gr.ImageMask라는 속성이 있었네요! 활용해서 문제를 해결해보겠습니당
