### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by ffe4el** [jbnu-orb/orb#24]
DB를 어떤것을 사용해보면 좋을지 discussion 해보면 좋을것 같습니다.
MySQL? or SQLite? or AWS S3?

**Comment by zzzz465** [comment]
S3 는 object storage 고 DB 가 아닙니다.
postgresql 이 가장 무난해요

**Comment by rladntlr** [comment]
유저 정보도 postgresql을 사용할까요?

**Comment by zzzz465** [comment]
> 유저 정보도 postgresql을 사용할까요?

디비는 하나로 통일합니다...
