### ISSUE TITLE
AI 모델 로컬 실행 실패

### ISSUE THREAD

**Issue by zzzz465** [jbnu-orb/orb#37]
dev 브랜치의 local/ 하위 모델 테스트 중 에러 발생해서 질문드립니다.

1. 왜 `main.py` 가 test/ 하위에 있나요?
2. python 버전이 몇인가요?
3. 설치 시도 시 아래처럼 로그 실패하는데, 패키지 버전 나열 안되어 있어서 `python -m venv .venv` 생성해서 clean 환경 생성한 다음 `pip freeze > requirements.txt` 로 패키지 버전 고정할 필요 있어보입니다

```sh
❯ pip install -r requirements.txt
Collecting pillow
  Using cached pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
Collecting numpy
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Collecting opencv-python
  Using cached opencv_python-4.10.0.82-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.5 MB)
Collecting scipy
  Using cached scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
Collecting tqdm
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Collecting matplotlib
  Using cached matplotlib-3.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
Collecting scikit-image
  Using cached scikit_image-0.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.7 MB)
Collecting replicate
  Using cached replicate-0.26.0-py3-none-any.whl (40 kB)
Collecting deepl
  Using cached deepl-1.18.0-py3-none-any.whl (35 kB)
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      /home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/jungooji/git/github-cloud/orb/local/.venv/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1ppfp42g', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ot__uuq2/dotenv_daa6eb7b89d1433a83738be7dc896cc3/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 641, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 787, in resolve
          dist = self._resolve_dist(
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 823, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1093, in best_match
          return self.obtain(req, installer)
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1104, in obtain
          return installer(requirement) if installer else None
        File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/jungooji/git/github-cloud/orb/local/.venv/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1ppfp42g', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by zzzz465** [comment]
또한 readme.md 내용대로 실행했더니 401 에러가 납니다.

```sh
Mask saved as './asset/mask.png'
# of pixels to be inpainted are 2371: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|2371/2371
Traceback (most recent call last):
  File "/home/jungooji/git/github-cloud/orb/local/test/main.py", line 71, in <module>
    main()
  File "/home/jungooji/git/github-cloud/orb/local/test/main.py", line 67, in main
    orb(org_img=args.img_path, mask_path='./asset/mask.png', output_path='./asset/result.png')
  File "/home/jungooji/git/github-cloud/orb/local/test/main.py", line 45, in orb
    img2prompt = replicate.run(
  File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/client.py", line 157, in run
    return run(self, ref, input, **params)
  File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/run.py", line 40, in run
    prediction = client.predictions.create(
  File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/prediction.py", line 463, in create
    resp = self._client._request(
  File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/client.py", line 87, in _request
    _raise_for_status(resp)
  File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/client.py", line 367, in _raise_for_status
    raise ReplicateError.from_response(resp)
replicate.exceptions.ReplicateError: ReplicateError Details:
title: Unauthenticated
status: 401
detail: You did not pass a valid authentication token
```

**Comment by zzzz465** [comment]
그리고 gitignore 도 추가 필요해보입니다

**Comment by riverallzero** [comment]
> 또한 readme.md 내용대로 실행했더니 401 에러가 납니다.
> 
> ```shell
> Mask saved as './asset/mask.png'
> # of pixels to be inpainted are 2371: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|2371/2371
> Traceback (most recent call last):
>   File "/home/jungooji/git/github-cloud/orb/local/test/main.py", line 71, in <module>
>     main()
>   File "/home/jungooji/git/github-cloud/orb/local/test/main.py", line 67, in main
>     orb(org_img=args.img_path, mask_path='./asset/mask.png', output_path='./asset/result.png')
>   File "/home/jungooji/git/github-cloud/orb/local/test/main.py", line 45, in orb
>     img2prompt = replicate.run(
>   File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/client.py", line 157, in run
>     return run(self, ref, input, **params)
>   File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/run.py", line 40, in run
>     prediction = client.predictions.create(
>   File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/prediction.py", line 463, in create
>     resp = self._client._request(
>   File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/client.py", line 87, in _request
>     _raise_for_status(resp)
>   File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/replicate/client.py", line 367, in _raise_for_status
>     raise ReplicateError.from_response(resp)
> replicate.exceptions.ReplicateError: ReplicateError Details:
> title: Unauthenticated
> status: 401
> detail: You did not pass a valid authentication token
> ```

@zzzz465, 토큰 키가 입력되지 않아 아래와 같은 에러가 발생하는 것 입니다.
노션에 토큰 키는 올려 둘 예정입니다.

**Comment by riverallzero** [comment]
> dev 브랜치의 local/ 하위 모델 테스트 중 에러 발생해서 질문드립니다.
> 
> 1. 왜 `main.py` 가 test/ 하위에 있나요?
> 2. python 버전이 몇인가요?
> 3. 설치 시도 시 아래처럼 로그 실패하는데, 패키지 버전 나열 안되어 있어서 `python -m venv .venv` 생성해서 clean 환경 생성한 다음 `pip freeze > requirements.txt` 로 패키지 버전 고정할 필요 있어보입니다
> 
> ```shell
> ❯ pip install -r requirements.txt
> Collecting pillow
>   Using cached pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
> Collecting numpy
>   Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
> Collecting opencv-python
>   Using cached opencv_python-4.10.0.82-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.5 MB)
> Collecting scipy
>   Using cached scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
> Collecting tqdm
>   Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
> Collecting matplotlib
>   Using cached matplotlib-3.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
> Collecting scikit-image
>   Using cached scikit_image-0.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.7 MB)
> Collecting replicate
>   Using cached replicate-0.26.0-py3-none-any.whl (40 kB)
> Collecting deepl
>   Using cached deepl-1.18.0-py3-none-any.whl (35 kB)
> Collecting dotenv
>   Using cached dotenv-0.0.5.tar.gz (2.4 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [77 lines of output]
>       /home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
>       !!
>       
>               ********************************************************************************
>               Requirements should be satisfied by a PEP 517 installer.
>               If you are using pip, you can try `pip install --use-pep517`.
>               ********************************************************************************
>       
>       !!
>         dist.fetch_build_eggs(dist.setup_requires)
>       WARNING: The wheel package is not available.
>         error: subprocess-exited-with-error
>       
>         × python setup.py egg_info did not run successfully.
>         │ exit code: 1
>         ╰─> [16 lines of output]
>             Traceback (most recent call last):
>               File "<string>", line 2, in <module>
>               File "<pip-setuptools-caller>", line 14, in <module>
>               File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/__init__.py", line 2, in <module>
>                 from setuptools.extension import Extension, Library
>               File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/extension.py", line 5, in <module>
>                 from setuptools.dist import _get_unpatched
>               File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/dist.py", line 7, in <module>
>                 from setuptools.command.install import install
>               File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/command/__init__.py", line 8, in <module>
>                 from setuptools.command import install_scripts
>               File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/setuptools/command/install_scripts.py", line 3, in <module>
>                 from pkg_resources import Distribution, PathMetadata, ensure_directory
>               File "/tmp/pip-wheel-dhjfjwm3/distribute_a83927e864384a40b071a23b05bffa31/pkg_resources.py", line 1518, in <module>
>                 register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
>             AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
>             [end of output]
>       
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>       error: metadata-generation-failed
>       
>       × Encountered error while generating package metadata.
>       ╰─> See above for output.
>       
>       note: This is an issue with the package mentioned above, not pip.
>       hint: See above for details.
>       Traceback (most recent call last):
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
>           subprocess.check_call(cmd)
>         File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['/home/jungooji/git/github-cloud/orb/local/.venv/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1ppfp42g', '--quiet', 'distribute']' returned non-zero exit status 1.
>       
>       The above exception was the direct cause of the following exception:
>       
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-ot__uuq2/dotenv_daa6eb7b89d1433a83738be7dc896cc3/setup.py", line 13, in <module>
>           setup(name='dotenv',
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
>           _install_setup_requires(attrs)
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
>           _fetch_build_eggs(dist)
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
>           dist.fetch_build_eggs(dist.setup_requires)
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 641, in fetch_build_eggs
>           return _fetch_build_eggs(self, requires)
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
>           resolved_dists = pkg_resources.working_set.resolve(
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 787, in resolve
>           dist = self._resolve_dist(
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 823, in _resolve_dist
>           dist = best[req.key] = env.best_match(
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1093, in best_match
>           return self.obtain(req, installer)
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1104, in obtain
>           return installer(requirement) if installer else None
>         File "/home/jungooji/git/github-cloud/orb/local/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
>           raise DistutilsError(str(e)) from e
>       distutils.errors.DistutilsError: Command '['/home/jungooji/git/github-cloud/orb/local/.venv/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1ppfp42g', '--quiet', 'distribute']' returned non-zero exit status 1.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```

local test를 위한 main파일입니다.
파이썬과 라이브러리 환경은 .environment 파일로 정리해두겠습니다.

**Comment by riverallzero** [comment]
@zzzz465 , 수정 완료하였으니 테스트 부탁드립니다.
